# This config file for Travis CI utilizes https://github.com/ros-planning/moveit_ci/ package.
sudo: required
dist: trusty  # distro used by Travis, moveit_ci uses the docker image's distro
services:
  - docker
language: cpp
cache: ccache
compiler: gcc

notifications:
  email:
    recipients:
      - lander@erlerobotics.com
      - anasarrak@erlerobotics.com

matrix:
  include:
    - os: linux
      dist: bionic
       services:
         - docker
       sudo:
         - required
    - os: osx
      osx_image: xcode10.1

before_script:
  #- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then . .travis.${TRAVIS_OS_NAME}.env; fi
  #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then . .travis.${TRAVIS_OS_NAME}.env; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bash ./osx-dependencies.sh; fi
  - mkdir /tmp/moveit2
  - mv * /tmp/moveit2
  #- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then git clone -q -b ros2 --depth=1 https://github.com/acutronicrobotics/moveit_ci.git .moveit_ci; fi

script:
  #- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then .moveit_ci/travis.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bash /tmp/moveit2/osx-dependencies.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bash /tmp/moveit2/osx-install-ros2-binary.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bash /tmp/moveit2/osx-compile-moveit2.sh; fi
