os:
  - linux
  - osx

sudo:
  - required

services:
  - docker

notifications:
  email:
    recipients:
      - lander@erlerobotics.com
      - anasarrak@erlerobotics.com

matrix:
  include:
    - os: linux
      dist: bionic
    - os: osx
      osx_image: xcode10.1

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bash osx.sh; fi
  - mkdir /tmp/moveit2; fi
  - mv * /tmp/moveit2; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd .docker/ci; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker build -t acutronicrobotics/moveit2 .; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker run -v /tmp/moveit2:/ros2_ws/src/moveit2 acutronicrobotics/moveit2; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then osx-compile.sh; fi
