sudo: required

dist: bionic

services:
  - docker
  
notifications:
  email:
    recipients:
      - lander@erlerobotics.com
      
before_script:
  - cd .docker/ci

script:
  - docker build -t acutronicrobotics/moveit2 .
